### PR TITLE
Many miscellaneous improvements

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Readjusted the codestyle to an .editorconfig file because it's an awful mess of tabs and spaces intermixed together
- Also added a .gitattributes file for automatic line ending normalization

### 2nd commit
- Use vector drawables for the menu item icons. This greatly improves how the toolbar looks.

### 3rd commit
- Rename id stuff to things that make more sense contextually
- Replace deprecated fill_parent with match_parent

### 4th commit
- A complete internal restructure of how preferences work and are handled. I'm kinda too tired to go into depth ATM but I can answer any questions you may have.
- Also deleted some unused preference-related strings

### 5th commit
- Remove extra padding to the left of the settings
- Replace Checkboxes with Switches as recommended by Material design

I tested and everything works normally. I can provide a test APK if needed.

### CODE REVIEW

**Comment by woheller69** [comment]
Thanks!

I renamed some methods and marked the prefKeys as translatable="false"

Do we really need this in build.gradle?         

    vectorDrawables.useSupportLibrary true

For me it works well without this line.

**Comment by woheller69** [comment]
I removed vectorDrawables.useSupportLibrary true
Also tested on Android 4.1.1 which is minSDK

**Comment by TacoTheDank** [comment]
> I renamed some methods and marked the prefKeys as translatable="false"

This didn't need to be done, as translatable="false" was [already there](https://github.com/woheller69/Level/pull/12/commits/77d1a06b4a9b84093b20459ba1b4232a489aec3e#diff-1855bd894ca5523c0d33a2d76a89aa31e8ee431401487b6a48f5474f1a78c819R2)

> Do we really need this in build.gradle?
> 
> ```
> vectorDrawables.useSupportLibrary true
> ```

For devices under Lollipop, this is likely necessary for the drawables to appear correctly. A lint appears when that gradle line isn't there: `Resource references will not work correctly in images generated for this vector icon for API < 21; check generated icon to make sure it looks acceptable`.

**Comment by woheller69** [comment]
I do not get that lint warning and it works well on Kitkat but nevertheless I added the line back in

**Pull request merged**
