### PR TITLE
Refactoring smoothing/averaging of sensor values.

### PR DESCRIPTION
**Pull request by lufebe16**
An exponential smoothing algorithm based on event timestamps has been added to OrientationProvider.

It replaces the viscosity emulating code in LevelPainter. And the heuristic code to calm down number displays is not needed any more.

Averaged values are now used for calibration rather than taking a single data point.

It will also have a calming effect on the number display

### CODE REVIEW

**Comment by woheller69** [comment]
Thanks, will have a look at it next week

**Comment by woheller69** [comment]
Nice idea, but the bubble behaves quite strange when the device is flat on the table.
The bubble behaves as if it was repelled by something

**Comment by lufebe16** [comment]
This is a problem that exists also in the current published version. Only the dynamics have changed. So it is more obvious.

The real problem is located in the code at the end of onOrientationChanged in LevelPainter. There is a 'correction des angles a plat - la bulle ne doit pas sortir du niveau'. The calculations are incorrect. They affect the angle in x (or y) when angle y (or x) is near zero. The digit display is not affected.

If that code is removed the problem disappears. But the bubble can go out of the circle, if not one of the angles is zero. So we would need a replacement.

**Comment by woheller69** [comment]
onOrientationChanged is only called when orientation is changed e.g. from Bottom to Landing.
But while we are in Landing mode this is not called anymore, so it cannot influence the behaviour of the bubble.

**Comment by woheller69** [comment]
Thanks, but I am still not convinced. I tested your fork on several devices and on older phones the movement of the bubble is not smooth. The bubble is moving in steps.
But I removed the stuff from onOrientationChanged and switched to your algo for keeping the bubble in the circle.

**Comment by lufebe16** [comment]
Thanks for the new arrows. It makes the look and feel more consistent over screens. And it adds the originally missing sign information to landing mode.

The problem of the bubble moving in steps could come from the eco mode (i.e. limiting the calculation to the framerate) introduced in onSensorChanged at the beginning. There is
`if (deltaTime < framedist) return;
`
Maybe it helps to remove that line.

But yes I can reproduce it on a samsung tablet  (about 10 years old) with a 32 bit equinox processor (and maybe soft float emulation!). So it might be the Math.pow call being to heavy for it.  Removing the eco mode here makes it even worse.

**Comment by lufebe16** [comment]
Here just my results of some timing tests, tested on an older device (10 years 32 bit) and a phone (5 years 64 bit) .

The pow function is out of scope. Also on the older device it needs 0 ms for dozens of measurments, before I see a single 1.

onSensorChanged delivers values with event-timestamps at a regular basis as expected. Values are 67 and 40 ms for the two devices.

Method onSensorChanged itself is called very irregularily on both devices. The difference between calls ranges from 5 to 120 ms (!). So that adds a big jitter to the updates in LevelPainter. Especially a 100 ms delay will be recognizable if applied directly to the screen graphics. An additional smoothing at the beginning of the draw process (~ 100 ms) is therefore still required.

The timing of the paint routine on both devices is equal and varies from 25 to 40 ms. So it does far not reach its limitation by 16 ms (frameRate).

**Comment by woheller69** [comment]
I have done some other tests and moved my simple (70/30) smoothing algorithm to orientation provider. 
That works but  causes other issues.
E.g. when locking the orientation the bubble does not move to the end anymore and even moves back when the angle is close to 90°.
So I tend to keep it as it is. When I revived the app I did not have the intention to reinvent it...

**Comment by woheller69** [comment]
Thanks for your proposals. There are also many things I would do differently in this app but I did not want to completely rewrite it.
I simply wanted to revive it as it had not been updated since 2014...

**Pull request closed without merging**
