### PR TITLE
A few miscellaneous QoL changes around the project

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Delete unnecessary project files
- Add generated APK directories to the .gitignore

### 2nd commit
- Update gradle wrapper to 7.3 using git bash

### 3rd commit
- Clean up the README a little bit

### 4th commit
- Same with the build.gradle files
- Update Android Gradle Plugin 4.1.2 -> 7.0.3
- Exclude unneeded META-INF from built APKs (shaves some kilobytes off the APK size)

### 5th commit
- Enable minification. This should shrink the app size on a device by a significant margin.

### 6th commit
- Use recommended FragmentContainerView for the SettingsActivity layout

### CODE REVIEW

**Comment by woheller69** [comment]
Thanks!
I only changed back to classpath "com.android.tools.build:gradle:4.1.2"
Otherwise my current Android Studio version does not work and I hate to upgrade it...

**Comment by TacoTheDank** [comment]
Very well, thanks!

**Comment by woheller69** [comment]
obviously F-Droid are having problems with the changes in gradle...
Build failed.

https://f-droid.org/wiki/page/org.woheller69.level/lastbuild_14

**Comment by TacoTheDank** [comment]
@woheller69 7.3 is a very new release, so they might not have added the hash on their end yet. I'm on phone right now, but I'll check when I get on the computer.

**Comment by woheller69** [comment]
I already asked. They need to fix it, nothing to do for me

**Comment by woheller69** [comment]
https://gitlab.com/fdroid/fdroidserver/-/merge_requests/1046/diffs?commit_id=c31490056e7cb0883a99bf57e8b3448668b201db

**Pull request merged**
